### ISSUE TITLE
Environment..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G3#54]
Which environment are you using for running the codes?

**Comment by WildJimmy** [comment]
I think @uarif is referring to where you write and test your code. I know a lot of people in this class like google colab, since it's online and you get to use a jupyter notebook which has some great functionality. Though personally I use Spyder (https://www.spyder-ide.org/) which is a local ide (mainly because this is how I learned Python and I'm too stubborn to change.)

**Comment by uarif** [comment]
> I think @uarif is referring to where you write and test your code. I know a lot of people in this class like google colab, since it's online and you get to use a jupyter notebook which has some great functionality. Though personally I use Spyder (https://www.spyder-ide.org/) which is a local ide (mainly because this is how I learned Python and I'm too stubborn to change.)

Ooh yes, I meant that, actually, I had some issues using google colab and the professor suggested using another environment. I also used the Python installed on my own computer. @JustinJaniszewski  No worries, thank you both.

**Comment by WildJimmy** [comment]
@uarif You're welcome, glad to help!
