### ISSUE TITLE
Create labels

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G3#6]
@WildJimmy since you are a maintainer also create some labels like:
- group discussion
- high priority
Also @JustinJaniszewski you may also write about what things are to be added to the labels.

**Comment by s4il3sh** [comment]
Also, you can labels like:
brainstorming

**Comment by s4il3sh** [comment]
Also add: check milestone

**Comment by s4il3sh** [comment]
& suggestion

**Comment by JustinJaniszewski** [comment]
high priority might be a good one (or "urgent!" or something like that). I don't believe your other suggestions are necessary since github as some default ones that cover those. An example is "enhancement". It is a default label meant for a "New feature or request". This would act in place of your "suggestion" label. We can discuss this again later if it seems one is necessary.

**Comment by WildJimmy** [comment]
This is a good idea. I'll be working on setting up the labels and milestones tonight so I'll be sure to incorporate these @s4il3sh @JustinJaniszewski

**Comment by JustinJaniszewski** [comment]
Sounds good

**Comment by WildJimmy** [comment]
I just added labels for High Priority, Suggestion, and Discussion, but I agree that I think the default labels are sufficient for other needs (I don't want to add too many labels, since I think it could get too specific at that point!)

**Comment by JustinJaniszewski** [comment]
I agree, also looks good!

**Comment by s4il3sh** [comment]
We need to add more labels. We have just added 2 labels. Need to add 8 more because adding labels has homework points.

**Comment by WildJimmy** [comment]
@s4il3sh yes this is true. I thought it was just for assigning labels but I think I was mistaken. I'll quick add those though it's kind of late at this point
