### ISSUE TITLE
Our target in the spring problem.

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G3#8]
Well, to create an algorithm, we need to have a of target what things we will be calculating. So, one thing is to find the spring constant of a spring system. What's next?
I guess we can add some other things too such as:
- find energy in the spring
- draw a graph of force vs. extension of the spring. (I can provide you with real data for this)
- maybe find its damping too

What else can we add?

**Comment by JustinJaniszewski** [comment]
I would like to start with a very simple example and make sure that it works as intended before moving on to more ambitious goals. These can be seperate issues for the algorithm milestone as well. For example, 1 issue for the simple example, another for damping, another for setting up a graph, etc.

**Comment by s4il3sh** [comment]
Also, if we could animate the system using Matplotlib or something? It would help us to visualize the system.

**Comment by WildJimmy** [comment]
Part of the project is to create a function, then to use that as an argument for another function. I think it's a good idea to find the spring potential energy, since I think it's reasonable to use the function for finding the spring constant as an argument for another function where we find the energy. Unless there's a way we can do this while finding the spring constant, but I'm not sure how that would be implemented without being a headache

**Comment by JustinJaniszewski** [comment]
I think we could do that, use two functions. First find the constant, then use it for the energy. 
First we could calculate and return the spring constant given the mass (at the end of a spring) and the position of the mass. Next, have a second function that uses the spring constant from the first as well as the position to calculate the energy.

**Comment by JustinJaniszewski** [comment]
I think this would be easiest to do assuming that the spring is connected to the ceiling with a mass at the end so we can easily set the force from the spring equal to the force of gravity
